import { CONFIG } from "@shared/model/config";
import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./schema/generated"; // generated by openapi-typescript

export const fetchClient = createFetchClient<paths>({
    baseUrl: CONFIG.API_BASE_URL,
});

export const rqClient = createClient(fetchClient);
